// This file is generated by dev/genItemTypesFromSchema.mjs
//
// Source: dev/Zotero-Source/resource/schema/global/schema.json
//
// Do not edit this file by hand. Re-run the generator instead.

export type ExtraValue = string | string[];
export type ExtraMap = Record<string, ExtraValue>;

export type CreatorType =
  | "artist"
  | "attorneyAgent"
  | "author"
  | "bookAuthor"
  | "cartographer"
  | "castMember"
  | "chair"
  | "commenter"
  | "composer"
  | "contributor"
  | "cosponsor"
  | "counsel"
  | "creator"
  | "director"
  | "editor"
  | "executiveProducer"
  | "guest"
  | "host"
  | "interviewee"
  | "interviewer"
  | "inventor"
  | "narrator"
  | "organizer"
  | "originalCreator"
  | "performer"
  | "podcaster"
  | "presenter"
  | "producer"
  | "programmer"
  | "recipient"
  | "reviewedAuthor"
  | "scriptwriter"
  | "seriesCreator"
  | "seriesEditor"
  | "sponsor"
  | "translator"
  | "wordsBy";

type CreatorPersonalName<T extends CreatorType = CreatorType> = {
  creatorType: T;
  firstName: string;
  lastName: string;
  name?: never;
};

type CreatorSingleName<T extends CreatorType = CreatorType> = {
  creatorType: T;
  firstName?: never;
  lastName?: never;
  name: string;
};

export type Creator<T extends CreatorType = CreatorType> =
  CreatorPersonalName<T> | CreatorSingleName<T>;

export type ItemType =
  | "artwork"
  | "audioRecording"
  | "bill"
  | "blogPost"
  | "book"
  | "bookSection"
  | "case"
  | "computerProgram"
  | "conferencePaper"
  | "dataset"
  | "dictionaryEntry"
  | "document"
  | "email"
  | "encyclopediaArticle"
  | "film"
  | "forumPost"
  | "hearing"
  | "instantMessage"
  | "interview"
  | "journalArticle"
  | "letter"
  | "magazineArticle"
  | "manuscript"
  | "map"
  | "newspaperArticle"
  | "patent"
  | "podcast"
  | "preprint"
  | "presentation"
  | "radioBroadcast"
  | "report"
  | "standard"
  | "statute"
  | "thesis"
  | "tvBroadcast"
  | "videoRecording"
  | "webpage";

export type ItemBase<T extends ItemType = ItemType> = {
  key: string;
  itemType: T;

  id: number;
  uri: string;
  year?: string;
  firstCreator?: string;

  title?: string;
  date?: string;

  /** Tags (list of tag names). */
  tags?: string[];

  /** Relations (predicates -> URIs). */
  relations?: Record<string, string[]>;

  /** Raw creators from toJSON(). */
  creators: Creator[];

  /** Parsed from Zotero's string `extra` field ("key: value" per line). */
  extra?: ExtraMap;

  /** Other fields from Zotero.Item.toJSON() */
  [field: string]: string;
};

export type ArtworkItem = ItemBase<"artwork"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  artworkMedium?: string;
  artworkSize?: string;
  callNumber?: string;
  citationKey?: string;
  eventPlace?: string;
  language?: string;
  libraryCatalog?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"artist" | "contributor">[];
};

export type AudioRecordingItem = ItemBase<"audioRecording"> & {
  DOI?: string;
  ISBN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  audioRecordingFormat?: string;
  callNumber?: string;
  citationKey?: string;
  label?: string;
  language?: string;
  libraryCatalog?: string;
  numberOfVolumes?: string;
  place?: string;
  rights?: string;
  runningTime?: string;
  seriesTitle?: string;
  shortTitle?: string;
  url?: string;
  volume?: string;
  creators?: Creator<
    | "composer"
    | "contributor"
    | "originalCreator"
    | "performer"
    | "translator"
    | "wordsBy"
  >[];
};

export type BillItem = ItemBase<"bill"> & {
  DOI?: string;
  accessDate?: string;
  billNumber?: string;
  citationKey?: string;
  code?: string;
  codePages?: string;
  codeVolume?: string;
  history?: string;
  language?: string;
  legislativeBody?: string;
  rights?: string;
  section?: string;
  session?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"contributor" | "cosponsor" | "sponsor">[];
};

export type BlogPostItem = ItemBase<"blogPost"> & {
  DOI?: string;
  ISSN?: string;
  accessDate?: string;
  blogTitle?: string;
  citationKey?: string;
  language?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  websiteType?: string;
  creators?: Creator<"author" | "commenter" | "contributor" | "translator">[];
};

export type BookItem = ItemBase<"book"> & {
  DOI?: string;
  ISBN?: string;
  ISSN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  edition?: string;
  format?: string;
  language?: string;
  libraryCatalog?: string;
  numPages?: string;
  numberOfVolumes?: string;
  originalDate?: string;
  originalPlace?: string;
  originalPublisher?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  series?: string;
  seriesNumber?: string;
  shortTitle?: string;
  url?: string;
  volume?: string;
  creators?: Creator<
    "author" | "contributor" | "editor" | "seriesEditor" | "translator"
  >[];
};

export type BookSectionItem = ItemBase<"bookSection"> & {
  DOI?: string;
  ISBN?: string;
  ISSN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  bookTitle?: string;
  callNumber?: string;
  citationKey?: string;
  edition?: string;
  format?: string;
  language?: string;
  libraryCatalog?: string;
  numberOfVolumes?: string;
  originalDate?: string;
  originalPlace?: string;
  originalPublisher?: string;
  pages?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  series?: string;
  seriesNumber?: string;
  shortTitle?: string;
  url?: string;
  volume?: string;
  creators?: Creator<
    | "author"
    | "bookAuthor"
    | "contributor"
    | "editor"
    | "seriesEditor"
    | "translator"
  >[];
};

export type CaseItem = ItemBase<"case"> & {
  DOI?: string;
  accessDate?: string;
  caseName?: string;
  citationKey?: string;
  court?: string;
  dateDecided?: string;
  docketNumber?: string;
  firstPage?: string;
  history?: string;
  language?: string;
  reporter?: string;
  reporterVolume?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"author" | "contributor" | "counsel">[];
};

export type ComputerProgramItem = ItemBase<"computerProgram"> & {
  DOI?: string;
  ISBN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  company?: string;
  libraryCatalog?: string;
  place?: string;
  programmingLanguage?: string;
  rights?: string;
  seriesTitle?: string;
  shortTitle?: string;
  system?: string;
  url?: string;
  versionNumber?: string;
  creators?: Creator<"contributor" | "programmer">[];
};

export type ConferencePaperItem = ItemBase<"conferencePaper"> & {
  DOI?: string;
  ISBN?: string;
  ISSN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  conferenceName?: string;
  eventPlace?: string;
  issue?: string;
  language?: string;
  libraryCatalog?: string;
  numberOfVolumes?: string;
  pages?: string;
  place?: string;
  proceedingsTitle?: string;
  publisher?: string;
  rights?: string;
  series?: string;
  seriesNumber?: string;
  shortTitle?: string;
  url?: string;
  volume?: string;
  creators?: Creator<
    "author" | "contributor" | "editor" | "seriesEditor" | "translator"
  >[];
};

export type DatasetItem = ItemBase<"dataset"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  format?: string;
  identifier?: string;
  language?: string;
  libraryCatalog?: string;
  repository?: string;
  repositoryLocation?: string;
  rights?: string;
  shortTitle?: string;
  type?: string;
  url?: string;
  versionNumber?: string;
  creators?: Creator<"author" | "contributor">[];
};

export type DictionaryEntryItem = ItemBase<"dictionaryEntry"> & {
  DOI?: string;
  ISBN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  dictionaryTitle?: string;
  edition?: string;
  language?: string;
  libraryCatalog?: string;
  numberOfVolumes?: string;
  pages?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  series?: string;
  seriesNumber?: string;
  shortTitle?: string;
  url?: string;
  volume?: string;
  creators?: Creator<
    "author" | "contributor" | "editor" | "seriesEditor" | "translator"
  >[];
};

export type DocumentItem = ItemBase<"document"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  language?: string;
  libraryCatalog?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  shortTitle?: string;
  type?: string;
  url?: string;
  creators?: Creator<
    "author" | "contributor" | "editor" | "reviewedAuthor" | "translator"
  >[];
};

export type EmailItem = ItemBase<"email"> & {
  DOI?: string;
  accessDate?: string;
  citationKey?: string;
  language?: string;
  rights?: string;
  shortTitle?: string;
  subject?: string;
  url?: string;
  creators?: Creator<"author" | "contributor" | "recipient" | "translator">[];
};

export type EncyclopediaArticleItem = ItemBase<"encyclopediaArticle"> & {
  DOI?: string;
  ISBN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  edition?: string;
  encyclopediaTitle?: string;
  language?: string;
  libraryCatalog?: string;
  numberOfVolumes?: string;
  pages?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  series?: string;
  seriesNumber?: string;
  shortTitle?: string;
  url?: string;
  volume?: string;
  creators?: Creator<
    "author" | "contributor" | "editor" | "seriesEditor" | "translator"
  >[];
};

export type FilmItem = ItemBase<"film"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  distributor?: string;
  genre?: string;
  language?: string;
  libraryCatalog?: string;
  place?: string;
  rights?: string;
  runningTime?: string;
  shortTitle?: string;
  url?: string;
  videoRecordingFormat?: string;
  creators?: Creator<
    | "castMember"
    | "contributor"
    | "director"
    | "guest"
    | "host"
    | "narrator"
    | "producer"
    | "scriptwriter"
    | "translator"
  >[];
};

export type ForumPostItem = ItemBase<"forumPost"> & {
  DOI?: string;
  accessDate?: string;
  citationKey?: string;
  forumTitle?: string;
  language?: string;
  postType?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"author" | "contributor">[];
};

export type HearingItem = ItemBase<"hearing"> & {
  DOI?: string;
  accessDate?: string;
  citationKey?: string;
  committee?: string;
  documentNumber?: string;
  history?: string;
  language?: string;
  legislativeBody?: string;
  numberOfVolumes?: string;
  pages?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  session?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"contributor">[];
};

export type InstantMessageItem = ItemBase<"instantMessage"> & {
  DOI?: string;
  accessDate?: string;
  citationKey?: string;
  language?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"author" | "contributor" | "recipient">[];
};

export type InterviewItem = ItemBase<"interview"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  interviewMedium?: string;
  language?: string;
  libraryCatalog?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<
    "contributor" | "interviewee" | "interviewer" | "translator"
  >[];
};

export type JournalArticleItem = ItemBase<"journalArticle"> & {
  DOI?: string;
  ISSN?: string;
  PMCID?: string;
  PMID?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  issue?: string;
  journalAbbreviation?: string;
  language?: string;
  libraryCatalog?: string;
  pages?: string;
  partNumber?: string;
  partTitle?: string;
  place?: string;
  publicationTitle?: string;
  publisher?: string;
  rights?: string;
  section?: string;
  series?: string;
  seriesText?: string;
  seriesTitle?: string;
  shortTitle?: string;
  url?: string;
  volume?: string;
  creators?: Creator<
    "author" | "contributor" | "editor" | "reviewedAuthor" | "translator"
  >[];
};

export type LetterItem = ItemBase<"letter"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  eventPlace?: string;
  language?: string;
  letterType?: string;
  libraryCatalog?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"author" | "contributor" | "recipient" | "translator">[];
};

export type MagazineArticleItem = ItemBase<"magazineArticle"> & {
  DOI?: string;
  ISSN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  issue?: string;
  language?: string;
  libraryCatalog?: string;
  pages?: string;
  place?: string;
  publicationTitle?: string;
  publisher?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  volume?: string;
  creators?: Creator<
    "author" | "contributor" | "reviewedAuthor" | "translator"
  >[];
};

export type ManuscriptItem = ItemBase<"manuscript"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  institution?: string;
  language?: string;
  libraryCatalog?: string;
  manuscriptType?: string;
  numPages?: string;
  number?: string;
  place?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"author" | "contributor" | "translator">[];
};

export type MapItem = ItemBase<"map"> & {
  DOI?: string;
  ISBN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  edition?: string;
  language?: string;
  libraryCatalog?: string;
  mapType?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  scale?: string;
  seriesTitle?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"cartographer" | "contributor" | "seriesEditor">[];
};

export type NewspaperArticleItem = ItemBase<"newspaperArticle"> & {
  DOI?: string;
  ISSN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  edition?: string;
  issue?: string;
  language?: string;
  libraryCatalog?: string;
  pages?: string;
  place?: string;
  publicationTitle?: string;
  publisher?: string;
  rights?: string;
  section?: string;
  shortTitle?: string;
  url?: string;
  volume?: string;
  creators?: Creator<
    "author" | "contributor" | "reviewedAuthor" | "translator"
  >[];
};

export type PatentItem = ItemBase<"patent"> & {
  DOI?: string;
  accessDate?: string;
  applicationNumber?: string;
  assignee?: string;
  citationKey?: string;
  country?: string;
  filingDate?: string;
  issueDate?: string;
  issuingAuthority?: string;
  language?: string;
  legalStatus?: string;
  pages?: string;
  patentNumber?: string;
  place?: string;
  priorityDate?: string;
  priorityNumbers?: string;
  references?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"attorneyAgent" | "contributor" | "inventor">[];
};

export type PodcastItem = ItemBase<"podcast"> & {
  DOI?: string;
  accessDate?: string;
  audioFileType?: string;
  citationKey?: string;
  episodeNumber?: string;
  language?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  runningTime?: string;
  seriesTitle?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<
    | "castMember"
    | "contributor"
    | "director"
    | "executiveProducer"
    | "guest"
    | "podcaster"
    | "producer"
    | "scriptwriter"
    | "seriesCreator"
    | "translator"
  >[];
};

export type PreprintItem = ItemBase<"preprint"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveID?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  genre?: string;
  language?: string;
  libraryCatalog?: string;
  place?: string;
  repository?: string;
  rights?: string;
  series?: string;
  seriesNumber?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<
    "author" | "contributor" | "editor" | "reviewedAuthor" | "translator"
  >[];
};

export type PresentationItem = ItemBase<"presentation"> & {
  DOI?: string;
  accessDate?: string;
  citationKey?: string;
  language?: string;
  meetingName?: string;
  place?: string;
  presentationType?: string;
  rights?: string;
  series?: string;
  sessionTitle?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<
    "chair" | "contributor" | "organizer" | "presenter" | "translator"
  >[];
};

export type RadioBroadcastItem = ItemBase<"radioBroadcast"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  audioRecordingFormat?: string;
  callNumber?: string;
  citationKey?: string;
  episodeNumber?: string;
  language?: string;
  libraryCatalog?: string;
  network?: string;
  place?: string;
  programTitle?: string;
  rights?: string;
  runningTime?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<
    | "castMember"
    | "contributor"
    | "creator"
    | "director"
    | "executiveProducer"
    | "guest"
    | "host"
    | "producer"
    | "scriptwriter"
    | "seriesCreator"
    | "translator"
  >[];
};

export type ReportItem = ItemBase<"report"> & {
  DOI?: string;
  ISBN?: string;
  ISSN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  institution?: string;
  language?: string;
  libraryCatalog?: string;
  pages?: string;
  place?: string;
  reportNumber?: string;
  reportType?: string;
  rights?: string;
  seriesNumber?: string;
  seriesTitle?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<
    "author" | "contributor" | "editor" | "seriesEditor" | "translator"
  >[];
};

export type StandardItem = ItemBase<"standard"> & {
  DOI?: string;
  ISBN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  committee?: string;
  edition?: string;
  language?: string;
  libraryCatalog?: string;
  numPages?: string;
  number?: string;
  organization?: string;
  partNumber?: string;
  partTitle?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  shortTitle?: string;
  status?: string;
  type?: string;
  url?: string;
  versionNumber?: string;
  creators?: Creator<"author" | "contributor" | "editor">[];
};

export type StatuteItem = ItemBase<"statute"> & {
  DOI?: string;
  accessDate?: string;
  citationKey?: string;
  code?: string;
  codeNumber?: string;
  dateEnacted?: string;
  history?: string;
  language?: string;
  nameOfAct?: string;
  pages?: string;
  publicLawNumber?: string;
  rights?: string;
  section?: string;
  session?: string;
  shortTitle?: string;
  url?: string;
  creators?: Creator<"author" | "contributor">[];
};

export type ThesisItem = ItemBase<"thesis"> & {
  DOI?: string;
  ISBN?: string;
  ISSN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  language?: string;
  libraryCatalog?: string;
  numPages?: string;
  place?: string;
  rights?: string;
  series?: string;
  seriesNumber?: string;
  shortTitle?: string;
  thesisType?: string;
  university?: string;
  url?: string;
  creators?: Creator<"author" | "contributor">[];
};

export type TvBroadcastItem = ItemBase<"tvBroadcast"> & {
  DOI?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  episodeNumber?: string;
  language?: string;
  libraryCatalog?: string;
  network?: string;
  place?: string;
  programTitle?: string;
  rights?: string;
  runningTime?: string;
  shortTitle?: string;
  url?: string;
  videoRecordingFormat?: string;
  creators?: Creator<
    | "castMember"
    | "contributor"
    | "director"
    | "executiveProducer"
    | "guest"
    | "host"
    | "narrator"
    | "producer"
    | "scriptwriter"
    | "seriesCreator"
    | "translator"
  >[];
};

export type VideoRecordingItem = ItemBase<"videoRecording"> & {
  DOI?: string;
  ISBN?: string;
  accessDate?: string;
  archive?: string;
  archiveLocation?: string;
  callNumber?: string;
  citationKey?: string;
  language?: string;
  libraryCatalog?: string;
  numberOfVolumes?: string;
  place?: string;
  rights?: string;
  runningTime?: string;
  seriesTitle?: string;
  shortTitle?: string;
  studio?: string;
  url?: string;
  videoRecordingFormat?: string;
  volume?: string;
  creators?: Creator<
    | "castMember"
    | "contributor"
    | "creator"
    | "director"
    | "executiveProducer"
    | "guest"
    | "host"
    | "narrator"
    | "producer"
    | "scriptwriter"
    | "translator"
  >[];
};

export type WebpageItem = ItemBase<"webpage"> & {
  DOI?: string;
  accessDate?: string;
  citationKey?: string;
  language?: string;
  place?: string;
  publisher?: string;
  rights?: string;
  shortTitle?: string;
  url?: string;
  websiteTitle?: string;
  websiteType?: string;
  creators?: Creator<"author" | "contributor" | "translator">[];
};
export type Item =
  | ArtworkItem
  | AudioRecordingItem
  | BillItem
  | BlogPostItem
  | BookItem
  | BookSectionItem
  | CaseItem
  | ComputerProgramItem
  | ConferencePaperItem
  | DatasetItem
  | DictionaryEntryItem
  | DocumentItem
  | EmailItem
  | EncyclopediaArticleItem
  | FilmItem
  | ForumPostItem
  | HearingItem
  | InstantMessageItem
  | InterviewItem
  | JournalArticleItem
  | LetterItem
  | MagazineArticleItem
  | ManuscriptItem
  | MapItem
  | NewspaperArticleItem
  | PatentItem
  | PodcastItem
  | PreprintItem
  | PresentationItem
  | RadioBroadcastItem
  | ReportItem
  | StandardItem
  | StatuteItem
  | ThesisItem
  | TvBroadcastItem
  | VideoRecordingItem
  | WebpageItem;
